-- CRIAR NOVO BD
CREATE DATABASE GREENHOUSE;
 
 -- UTILIZANDO BD
 USE GREENHOUSE;
 
 -- CRIANDO UMA TABELA
 CREATE TABLE `GREENHOUSE`.`PLANTS`(
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL
		DEFAULT CURRENT_TIMESTAMP ON
        UPDATE CURRENT_TIMESTAMP,
        `SENSOR_LEVEL` CHAR(5) DEFAULT NULL,
        PRIMARY KEY `PK_PLANT_NAME`(`PLANT_NAME`)
        );

-- COMANDOS DML DE INSERÇÃO DE DADOS
INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('ORQUIDEA', 10, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('SUCULENTA', 8, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('BROMELIA', 2, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('COQUEIRO', 15, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('SAKURA', 3, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('DIAMBA', 420, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('GIRASSOL', 20, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('VIOLETA', 11, 'HIGH');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('ERVADAJAMAICA', 666, 'LOW');

INSERT INTO `GREENHOUSE`.`PLANTS`
(`PLANT_NAME`, `SENSOR_VALUE`, `SENSOR_LEVEL`)
VALUES('TOMATEIRO', 22, 'HIGH');

-- EXECUTANDO COMANDOS DQL - SELECT
-- CONSULTANDO TUDO DA TABELA
SELECT * FROM `GREENHOUSE`.`PLANTS`;

-- ESPECIFICANDO APENAS AS COLUNAS DESEJADAS
SELECT `PLANT_NAME`,  `SENSOR_EVENT`
FROM `PLANTS`;

-- APLICAR FILTROS NOS REGISTROS DE DADOS
SELECT * 
FROM PLANTS
WHERE SENSOR_LEVEL = 'HIGH'
AND SENSOR_VALUE >= 10 AND SENSOR_VALUE <=20;

SELECT *
FROM PLANTS
WHERE SENSOR_LEVEL IN ('HIGH', 'LOW');

-- CLAUSULA DE ORDENAÇÃO 
SELECT *
FROM PLANTS
WHERE SENSOR_VALUE < 420 
ORDER BY SENSOR_VALUE DESC;

-- FUNÇÕES DE AGRUPAMENTO
SELECT COUNT(*), SENSOR_LEVEL
FROM PLANTS
GROUP BY SENSOR_LEVEL;

-- SQL SELECT TOP
SELECT *
FROM PLANTS
WHERE SENSOR_VALUE < 1000
LIMIT 3;

-- SQL MIN AND MAX
SELECT MIN(SENSOR_VALUE)
FROM PLANTS
WHERE SENSOR_LEVEL = 'LOW';

SELECT MAX(SENSOR_VALUE)
FROM PLANTS
WHERE SENSOR_LEVEL = 'HIGH';

-- SQL SUM
SELECT SUM(SENSOR_VALUE)
FROM PLANTS;

-- SQL AVG
SELECT AVG(SENSOR_VALUE)
FROM PLANTS