USE `bd2401`;
-- Excluindo o BD
-- DROP DATABASE `bd2401`;
-- Criando o Schema do BD
-- CREATE SCHEMA `bd2401`;
-- Criando a tabela
CREATE TABLE `bd2401`. `NEW_TABLE`(
	`ID_MEMBER` INT NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(20) NOT NULL,
    `ACTIVE` BIT(1) NULL DEFAULT 1,
    `WHEN_ADDED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY(`ID_MEMBER`) 
);


-- inserindo dados na tabela
INSERT INTO `bd2401` . `NEW_TABLE` (`FIRST_NAME`)
VALUES('Camilly Volk');

INSERT INTO `bd2401` . `NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES('Arthur Dambros', 0);

INSERT INTO `bd2401` . `NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES('Claudia Volk', 0);

-- exibindo/consultando dados
SELECT * FROM `bd2401` . `NEW_TABLE`;